ROOTDIR = $(PROJ_HOME)/protocol/diameter/tayana/src

include $(ROOTDIR)/makeutil/header.top
######################################################################
# define the list of directories
DIRS =   base\
	 rx\
	 sy\
	 gx\
         ro\
	 re\
	 rc\
         s6a\
         slh\
         sd\
         sh\
         cx\

######################################################################

include $(ROOTDIR)/makeutil/footer.top
